require 'spec_helper'

describe PeopleHelper do
  
  describe "populate resource" do
    it "populated unsaved resource object with data from params" do
      resource = Person.new
      params[:person] = {:email => 'mind@apples.com',
                         :login => 'calm_mind',
                         :some_value => 'artifical'}

      helper.populate_resource(resource)

      resource.email.should == 'mind@apples.com'
      resource.login.should == 'calm_mind'
      resource.some_value.should == 'artifical'
    end

    it "doesn't populate empty login'" do
      resource = Person.new
      params[:person] = {:email => 'mind@apples.com',
                         :login => '',
                         :some_value => 'artifical'}

      helper.populate_resource(resource)
      resource.login.should_not == 'calm_mind'
    end
  end

  describe "person_link" do
    it "return proper person name" do
      person = Factory(:person, :login => "apples_mind", :name => "Mind apples user")
      mindapple = Factory(:mindapple, :person => person)

      helper.person_link(mindapple).should == "<a href=\"/person/apples_mind\">Mind apples user</a>"
    end

    it "return login name if there is no user name" do
      person = Factory(:person, :login => "apples_mind", :name => "")
      mindapple = Factory(:mindapple, :person => person)

      helper.person_link(mindapple).should == "<a href=\"/person/apples_mind\">apples_mind</a>"
    end

    it "return anonym for autogenerated user" do
      person = Factory(:person, :login => "autogen_asadsda", :name => "", :page_code => "asadsda")
      mindapple = Factory(:mindapple, :person => person)

      helper.person_link(mindapple).should == "anonymous"
    end

    it "return name without link for autogenerated user with name" do
      person = Factory(:person, :login => "autogen_asadsda", :name => "Andyyy", :page_code => "asadsda")
      mindapple = Factory(:mindapple, :person => person)

      helper.person_link(mindapple).should == "Andyyy"
    end

    it "return anonymous name without link for user with private profile" do
     self.stubs(:current_user).returns  Factory(:person, :name => "someone else")
      person = Factory(:person, :login => "apples_mind", :name => "Mind apples user", :public_profile => false)
      mindapple = Factory(:mindapple, :person => person)

      helper.person_link(mindapple).should == "anonymous"
    end

    it "return name with link for logged user with private profile" do
      self.stubs(:current_user).returns  Factory(:person, :name => "someone else")
      person = Factory(:person, :login => "apples_mind", :name => "Mind apples user", :public_profile => false)
      mindapple = Factory(:mindapple,:person => person)

      helper.person_link(mindapple).should == "anonymous"
    end

    it "return name with link for logged user with private profile" do
      person = Factory(:person, :login => "apples_mind", :name => "Mind apples user", :public_profile => false)
      self.stubs(:current_user).returns  person
      mindapple = Factory(:mindapple, :person => person)

      helper.person_link(mindapple).should == "<a href=\"/person/apples_mind\">Mind apples user</a>"
    end
  end

  context "for logged user" do
    it "return true if match with given user" do
      person = Factory(:person, :login => "apples_mind")
      self.stubs(:current_user).returns  person

      helper.match_logger_user?(person).should be_true
    end

    it "return false if match with given user" do
      person = Factory(:person, :login => "apples_mind")
      person2 = Factory(:person, :login => "brain")
      self.stubs(:current_user).returns  person2

      helper.match_logger_user?(person).should be_false
    end
  end

  describe "suggestion" do
    before(:each) do
      session[:suggestions] = {'0' => {"suggestion" => 'riding on the wolf'},
                               '1' => {"suggestion" =>'swiming with sharks'},
                               '2' => {"suggestion" =>'wrestling with the bears'},
                               '3' => {"suggestion" =>''},
                               '4' => {"suggestion" =>'feading lions'}
                               }
    end

    it "return suggestion from session" do
      helper.suggestion(1).should == 'swiming with sharks'
    end

    it "clear session with suggestions" do
      helper.suggestion(4).should == 'feading lions'
      session[:suggestions].should == nil
    end

  end
end
