@pivotal_1292369
@pivotal_4030096

Feature: Anonymous personal page

  Scenario: Person sees his page
    When I go to the "take the test" page
    And I check "person_policy_checked"
    And I press "Submit"
    Then I should see "Your page on Mindapples"

  Scenario: Login is not validate if is autogenerated
    Given I am on the "take the test" page
    And I press "Submit"
    And I check "person_policy_checked"
    And I press "Submit"
    Then I should not see "Login can not start with 'autogen_'"
    And I should see "Your page on Mindapples"

  Scenario: Sombody else sees his page
    Given I have a personal page
    When I go to my mindapples page
    Then I should see "Somebody's page on Mindapples"
